#!/bin/bash
# Skill Path Resolver - Bash Version
# 
# Source this file to get helper functions:
#   source resolver.sh
#
# Or run directly:
#   ./resolver.sh detect
#   ./resolver.sh export

set -e

# ============================================================
# Configuration
# ============================================================

KNOWN_PATHS=(
    "/mnt/skills/user"
    "/mnt/skills/public"
    "$HOME/.gemini/skills"
    "$HOME/gemini/skills"
    ".gemini/skills"
)

# ============================================================
# Core Functions
# ============================================================

detect_skills_root() {
    # 1. Check environment variable
    if [[ -n "$SKILLS_ROOT" && -d "$SKILLS_ROOT" ]]; then
        echo "$SKILLS_ROOT"
        return 0
    fi
    
    # 2. Check known locations
    for path in "${KNOWN_PATHS[@]}"; do
        expanded=$(eval echo "$path")
        if [[ -d "$expanded" ]]; then
            echo "$expanded"
            return 0
        fi
    done
    
    # 3. Try to detect from script location
    local script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local potential_root="$(dirname "$(dirname "$script_dir")")"
    if [[ -d "$potential_root/skill-path-resolver" ]]; then
        echo "$potential_root"
        return 0
    fi
    
    # 4. Fallback
    echo "$(pwd)"
    return 1
}

get_skills_root() {
    if [[ -z "$SKILLS_ROOT" ]]; then
        SKILLS_ROOT=$(detect_skills_root)
    fi
    echo "$SKILLS_ROOT"
}

get_skill_path() {
    local skill_name="$1"
    local subpath="${2:-}"
    
    local root=$(get_skills_root)
    if [[ -n "$subpath" ]]; then
        echo "$root/$skill_name/$subpath"
    else
        echo "$root/$skill_name"
    fi
}

resolve_skill_path() {
    local from_skill="$1"
    local to_skill="$2"
    
    # Calculate relative path
    # From: skills_root/from_skill/scripts
    # To: skills_root/to_skill/scripts
    echo "../../$to_skill/scripts"
}

list_skills() {
    local root=$(get_skills_root)
    
    for dir in "$root"/*/; do
        local skill_name=$(basename "$dir")
        if [[ -f "$dir/SKILL.md" ]] || [[ -d "$dir/scripts" ]]; then
            echo "$skill_name"
        fi
    done
}

# ============================================================
# Detection Report
# ============================================================

print_detection_report() {
    local root=$(get_skills_root)
    local method="directory_scan"
    local confidence="MEDIUM"
    
    if [[ -n "$SKILLS_ROOT" ]]; then
        method="environment_variable"
        confidence="HIGH"
    fi
    
    echo "Environment Detection Report"
    echo "========================================"
    echo "Detected SKILLS_ROOT: $root"
    echo "Detection Method: $method"
    echo "Confidence: $confidence"
    echo ""
    echo "Found Skills:"
    
    for skill in $(list_skills); do
        echo "  ✓ $skill"
    done
}

# ============================================================
# Export Configuration
# ============================================================

export_bash_config() {
    local root=$(get_skills_root)
    
    cat << EOF
# Skill Path Configuration
# Generated by skill-path-resolver

export SKILLS_ROOT="$root"

# Helper function to get skill path
get_skill_path() {
    echo "\$SKILLS_ROOT/\$1"
}

# Verify setup
if [ -d "\$SKILLS_ROOT" ]; then
    echo "✓ SKILLS_ROOT set to: \$SKILLS_ROOT"
else
    echo "✗ Warning: SKILLS_ROOT directory not found: \$SKILLS_ROOT"
fi
EOF
}

export_fish_config() {
    local root=$(get_skills_root)
    
    cat << EOF
# Skill Path Configuration
# Generated by skill-path-resolver

set -gx SKILLS_ROOT "$root"

function get_skill_path
    echo "\$SKILLS_ROOT/\$argv[1]"
end
EOF
}

export_json_config() {
    local root=$(get_skills_root)
    local skills=$(list_skills | tr '\n' ',' | sed 's/,$//')
    
    cat << EOF
{
  "SKILLS_ROOT": "$root",
  "found_skills": [$(echo "$skills" | sed 's/,/", "/g' | sed 's/^/"/' | sed 's/$/"/')]
}
EOF
}

# ============================================================
# Main
# ============================================================

main() {
    local command="${1:-help}"
    
    case "$command" in
        detect)
            print_detection_report
            ;;
        export)
            local shell="${2:-bash}"
            case "$shell" in
                bash|zsh)
                    export_bash_config
                    ;;
                fish)
                    export_fish_config
                    ;;
                json)
                    export_json_config
                    ;;
                *)
                    echo "Unknown shell: $shell"
                    exit 1
                    ;;
            esac
            ;;
        list)
            list_skills
            ;;
        root)
            get_skills_root
            ;;
        help|--help|-h)
            echo "Usage: $0 <command> [options]"
            echo ""
            echo "Commands:"
            echo "  detect          Detect environment and list skills"
            echo "  export [shell]  Export configuration (bash, zsh, fish, json)"
            echo "  list            List found skills"
            echo "  root            Print SKILLS_ROOT path"
            echo ""
            echo "Examples:"
            echo "  $0 detect"
            echo "  $0 export bash > setup.sh && source setup.sh"
            echo "  source $0  # Load helper functions"
            ;;
        *)
            echo "Unknown command: $command"
            echo "Run '$0 help' for usage"
            exit 1
            ;;
    esac
}

# If script is executed (not sourced), run main
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
